# Generated by Django 4.2.1 on 2023-06-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(default=1, max_length=1000000),
            preserve_default=False,
        ),
    ]
