# Generated by Django 4.2.1 on 2023-07-01 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_userprofile_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_agenda',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='event_aim',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='event_guest_speakers',
            field=models.CharField(default=1, max_length=1000000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='event_organizer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='event.userprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='event_ticket_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
