# Generated by Django 4.2.1 on 2023-07-01 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_event_event_agenda_event_event_aim_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_aim',
        ),
    ]
