# Generated by Django 4.2.1 on 2023-07-01 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_remove_event_event_aim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_ticket_price',
            field=models.FloatField(blank=True),
        ),
    ]
