# Generated by Django 4.2.1 on 2023-07-01 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_event_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_registered_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events_registered_count', models.IntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.userprofile')),
            ],
        ),
    ]
