# Generated by Django 4.2.1 on 2023-07-01 05:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_event_event_registered_count_eventregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='id_event',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
