# Generated by Django 4.2.1 on 2023-07-01 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_eventnotification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventNotification',
        ),
    ]
